"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing
if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never
DESCRIPTOR: _descriptor.FileDescriptor

class _RobotControlType:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _RobotControlTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RobotControlType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    OLD_FORMAT: _RobotControlType.ValueType
    KICKER_AND_DRIBBLER: _RobotControlType.ValueType
    SPEED_CONTROL: _RobotControlType.ValueType
    COORDINATE_CONTROL: _RobotControlType.ValueType
    GLOBAL_COORDINATES: _RobotControlType.ValueType
    CAP_VEL_AND_ACCEL: _RobotControlType.ValueType

class RobotControlType(_RobotControlType, metaclass=_RobotControlTypeEnumTypeWrapper):
    ...
OLD_FORMAT: RobotControlType.ValueType
KICKER_AND_DRIBBLER: RobotControlType.ValueType
SPEED_CONTROL: RobotControlType.ValueType
COORDINATE_CONTROL: RobotControlType.ValueType
GLOBAL_COORDINATES: RobotControlType.ValueType
CAP_VEL_AND_ACCEL: RobotControlType.ValueType
Global___RobotControlType: _TypeAlias = RobotControlType

class _KickerMode:
    ValueType = _typing.NewType('ValueType', _builtins.int)
    V: _TypeAlias = ValueType

class _KickerModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_KickerMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    IDLE: _KickerMode.ValueType
    KICK_STRAIGHT: _KickerMode.ValueType
    KICK_HIGH: _KickerMode.ValueType
    AUTOKICK_STRAIGHT: _KickerMode.ValueType
    AUTOKICK_HIGH: _KickerMode.ValueType

class KickerMode(_KickerMode, metaclass=_KickerModeEnumTypeWrapper):
    ...
IDLE: KickerMode.ValueType
KICK_STRAIGHT: KickerMode.ValueType
KICK_HIGH: KickerMode.ValueType
AUTOKICK_STRAIGHT: KickerMode.ValueType
AUTOKICK_HIGH: KickerMode.ValueType
Global___KickerMode: _TypeAlias = KickerMode

@_typing.final
class OldFormat(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    VEL_X_FIELD_NUMBER: _builtins.int
    VEL_Y_FIELD_NUMBER: _builtins.int
    ANGULAR_VELOCITY_OR_DELTA_ANGLE_FIELD_NUMBER: _builtins.int
    KICKER_SETTING_FIELD_NUMBER: _builtins.int
    DRIBBLER_SETTING_FIELD_NUMBER: _builtins.int
    AUTOKICK_STRAIGHT_FIELD_NUMBER: _builtins.int
    AUTOKICK_HIGH_FIELD_NUMBER: _builtins.int
    KICK_STRAIGHT_FIELD_NUMBER: _builtins.int
    KICK_HIGH_FIELD_NUMBER: _builtins.int
    ANGVEL_ANGLE_TOGGLE_FIELD_NUMBER: _builtins.int
    DRIBBLER_IS_ENABLED_FIELD_NUMBER: _builtins.int
    HIGH_VOLTAGE_FIELD_NUMBER: _builtins.int
    vel_x: _builtins.int
    vel_y: _builtins.int
    angular_velocity_or_delta_angle: _builtins.int
    kicker_setting: _builtins.int
    dribbler_setting: _builtins.int
    autokick_straight: _builtins.bool
    autokick_high: _builtins.bool
    kick_straight: _builtins.bool
    kick_high: _builtins.bool
    angvel_angle_toggle: _builtins.bool
    dribbler_is_enabled: _builtins.bool
    high_voltage: _builtins.bool

    def __init__(self, *, vel_x: _builtins.int | None=..., vel_y: _builtins.int | None=..., angular_velocity_or_delta_angle: _builtins.int | None=..., kicker_setting: _builtins.int | None=..., dribbler_setting: _builtins.int | None=..., autokick_straight: _builtins.bool | None=..., autokick_high: _builtins.bool | None=..., kick_straight: _builtins.bool | None=..., kick_high: _builtins.bool | None=..., angvel_angle_toggle: _builtins.bool | None=..., dribbler_is_enabled: _builtins.bool | None=..., high_voltage: _builtins.bool | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['angular_velocity_or_delta_angle', b'angular_velocity_or_delta_angle', 'angvel_angle_toggle', b'angvel_angle_toggle', 'autokick_high', b'autokick_high', 'autokick_straight', b'autokick_straight', 'dribbler_is_enabled', b'dribbler_is_enabled', 'dribbler_setting', b'dribbler_setting', 'high_voltage', b'high_voltage', 'kick_high', b'kick_high', 'kick_straight', b'kick_straight', 'kicker_setting', b'kicker_setting', 'vel_x', b'vel_x', 'vel_y', b'vel_y']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['angular_velocity_or_delta_angle', b'angular_velocity_or_delta_angle', 'angvel_angle_toggle', b'angvel_angle_toggle', 'autokick_high', b'autokick_high', 'autokick_straight', b'autokick_straight', 'dribbler_is_enabled', b'dribbler_is_enabled', 'dribbler_setting', b'dribbler_setting', 'high_voltage', b'high_voltage', 'kick_high', b'kick_high', 'kick_straight', b'kick_straight', 'kicker_setting', b'kicker_setting', 'vel_x', b'vel_x', 'vel_y', b'vel_y']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...

    def WhichOneof(self, oneof_group: _Never) -> None:
        ...
Global___OldFormat: _TypeAlias = OldFormat

@_typing.final
class KickerAndDribbler(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    KICKER_MODE_FIELD_NUMBER: _builtins.int
    KICKER_SETTING_FIELD_NUMBER: _builtins.int
    DRIBBLER_SETTING_FIELD_NUMBER: _builtins.int
    kicker_mode: Global___KickerMode.ValueType
    kicker_setting: _builtins.int
    dribbler_setting: _builtins.int

    def __init__(self, *, kicker_mode: Global___KickerMode.ValueType | None=..., kicker_setting: _builtins.int | None=..., dribbler_setting: _builtins.int | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['dribbler_setting', b'dribbler_setting', 'kicker_mode', b'kicker_mode', 'kicker_setting', b'kicker_setting']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['dribbler_setting', b'dribbler_setting', 'kicker_mode', b'kicker_mode', 'kicker_setting', b'kicker_setting']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...

    def WhichOneof(self, oneof_group: _Never) -> None:
        ...
Global___KickerAndDribbler: _TypeAlias = KickerAndDribbler

@_typing.final
class SpeedControl(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    VEL_X_FIELD_NUMBER: _builtins.int
    VEL_Y_FIELD_NUMBER: _builtins.int
    ANGULAR_VELOCITY_FIELD_NUMBER: _builtins.int
    DELTA_ANGLE_FIELD_NUMBER: _builtins.int
    vel_x: _builtins.float
    '[m/s]'
    vel_y: _builtins.float
    '[m/s]'
    angular_velocity: _builtins.float
    '[rad/s]'
    delta_angle: _builtins.float
    '[rad]'

    def __init__(self, *, vel_x: _builtins.float | None=..., vel_y: _builtins.float | None=..., angular_velocity: _builtins.float | None=..., delta_angle: _builtins.float | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['angular_velocity', b'angular_velocity', 'angular_velocity_or_angle', b'angular_velocity_or_angle', 'delta_angle', b'delta_angle', 'vel_x', b'vel_x', 'vel_y', b'vel_y']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['angular_velocity', b'angular_velocity', 'angular_velocity_or_angle', b'angular_velocity_or_angle', 'delta_angle', b'delta_angle', 'vel_x', b'vel_x', 'vel_y', b'vel_y']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
    _WhichOneofReturnType_angular_velocity_or_angle: _TypeAlias = _typing.Literal['angular_velocity', 'delta_angle']
    _WhichOneofArgType_angular_velocity_or_angle: _TypeAlias = _typing.Literal['angular_velocity_or_angle', b'angular_velocity_or_angle']

    def WhichOneof(self, oneof_group: _WhichOneofArgType_angular_velocity_or_angle) -> _WhichOneofReturnType_angular_velocity_or_angle | None:
        ...
Global___SpeedControl: _TypeAlias = SpeedControl

@_typing.final
class Target(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    ID_FIELD_NUMBER: _builtins.int
    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    VX_FIELD_NUMBER: _builtins.int
    VY_FIELD_NUMBER: _builtins.int
    ANGLE_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    x: _builtins.float
    '[m]'
    y: _builtins.float
    '[m]'
    vx: _builtins.float
    '[m/s]'
    vy: _builtins.float
    '[m/s]'
    angle: _builtins.float
    '[rad]'

    def __init__(self, *, id: _builtins.int | None=..., x: _builtins.float | None=..., y: _builtins.float | None=..., vx: _builtins.float | None=..., vy: _builtins.float | None=..., angle: _builtins.float | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['angle', b'angle', 'id', b'id', 'vx', b'vx', 'vy', b'vy', 'x', b'x', 'y', b'y']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['angle', b'angle', 'id', b'id', 'vx', b'vx', 'vy', b'vy', 'x', b'x', 'y', b'y']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...

    def WhichOneof(self, oneof_group: _Never) -> None:
        ...
Global___Target: _TypeAlias = Target

@_typing.final
class CoordinateControl(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    TARGETS_FIELD_NUMBER: _builtins.int

    @_builtins.property
    def targets(self) -> _containers.RepeatedCompositeFieldContainer[Global___Target]:
        ...

    def __init__(self, *, targets: _abc.Iterable[Global___Target] | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _Never

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['targets', b'targets']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...

    def WhichOneof(self, oneof_group: _Never) -> None:
        ...
Global___CoordinateControl: _TypeAlias = CoordinateControl

@_typing.final
class GlobalCoordinates(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    ANGLE_FIELD_NUMBER: _builtins.int
    x: _builtins.float
    '[m]'
    y: _builtins.float
    '[m]'
    angle: _builtins.float
    '[rad]'

    def __init__(self, *, x: _builtins.float | None=..., y: _builtins.float | None=..., angle: _builtins.float | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['angle', b'angle', 'x', b'x', 'y', b'y']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['angle', b'angle', 'x', b'x', 'y', b'y']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...

    def WhichOneof(self, oneof_group: _Never) -> None:
        ...
Global___GlobalCoordinates: _TypeAlias = GlobalCoordinates

@_typing.final
class CapVelAndAccel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    MAX_VEL_FIELD_NUMBER: _builtins.int
    MAX_ACCEL_FIELD_NUMBER: _builtins.int
    max_vel: _builtins.float
    '[m/s]'
    max_accel: _builtins.float
    '[m/s^2]'

    def __init__(self, *, max_vel: _builtins.float | None=..., max_accel: _builtins.float | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['max_accel', b'max_accel', 'max_vel', b'max_vel']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['max_accel', b'max_accel', 'max_vel', b'max_vel']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...

    def WhichOneof(self, oneof_group: _Never) -> None:
        ...
Global___CapVelAndAccel: _TypeAlias = CapVelAndAccel

@_typing.final
class RobotCommand(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    ROBOT_ID_FIELD_NUMBER: _builtins.int
    OLD_FORMAT_FIELD_NUMBER: _builtins.int
    KICKER_AND_DRIBBLER_FIELD_NUMBER: _builtins.int
    SPEED_CONTROL_FIELD_NUMBER: _builtins.int
    COORDINATE_CONTROL_FIELD_NUMBER: _builtins.int
    GLOBAL_COORDINATES_FIELD_NUMBER: _builtins.int
    CAP_VEL_AND_ACCEL_FIELD_NUMBER: _builtins.int
    robot_id: _builtins.int
    'optional so that it always prints when id is 0\n    https://stackoverflow.com/questions/47373976/why-is-my-protobuf-message-in-python-ignoring-zero-values\n    '

    @_builtins.property
    def old_format(self) -> Global___OldFormat:
        ...

    @_builtins.property
    def kicker_and_dribbler(self) -> Global___KickerAndDribbler:
        ...

    @_builtins.property
    def speed_control(self) -> Global___SpeedControl:
        ...

    @_builtins.property
    def coordinate_control(self) -> Global___CoordinateControl:
        ...

    @_builtins.property
    def global_coordinates(self) -> Global___GlobalCoordinates:
        ...

    @_builtins.property
    def cap_vel_and_accel(self) -> Global___CapVelAndAccel:
        ...

    def __init__(self, *, robot_id: _builtins.int | None=..., old_format: Global___OldFormat | None=..., kicker_and_dribbler: Global___KickerAndDribbler | None=..., speed_control: Global___SpeedControl | None=..., coordinate_control: Global___CoordinateControl | None=..., global_coordinates: Global___GlobalCoordinates | None=..., cap_vel_and_accel: Global___CapVelAndAccel | None=...) -> None:
        ...
    _HasFieldArgType: _TypeAlias = _typing.Literal['cap_vel_and_accel', b'cap_vel_and_accel', 'control', b'control', 'coordinate_control', b'coordinate_control', 'global_coordinates', b'global_coordinates', 'kicker_and_dribbler', b'kicker_and_dribbler', 'old_format', b'old_format', 'robot_id', b'robot_id', 'speed_control', b'speed_control']

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool:
        ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal['cap_vel_and_accel', b'cap_vel_and_accel', 'control', b'control', 'coordinate_control', b'coordinate_control', 'global_coordinates', b'global_coordinates', 'kicker_and_dribbler', b'kicker_and_dribbler', 'old_format', b'old_format', 'robot_id', b'robot_id', 'speed_control', b'speed_control']

    def ClearField(self, field_name: _ClearFieldArgType) -> None:
        ...
    _WhichOneofReturnType_control: _TypeAlias = _typing.Literal['old_format', 'kicker_and_dribbler', 'speed_control', 'coordinate_control', 'global_coordinates', 'cap_vel_and_accel']
    _WhichOneofArgType_control: _TypeAlias = _typing.Literal['control', b'control']

    def WhichOneof(self, oneof_group: _WhichOneofArgType_control) -> _WhichOneofReturnType_control | None:
        ...
Global___RobotCommand: _TypeAlias = RobotCommand